SEED_QUESTIONS = [
    {
        "topic": "python",
        "type": "choice",
        "prompt": "Что выведет print(2 + 3)?",
        "options": ["5", "23", "Ошибка"],
        "correct_answers": ["5"],
        "explanation": "Оператор + складывает числа, поэтому результат равен 5.",
        "order_index": 1,
    },
    {
        "topic": "python",
        "type": "input",
        "prompt": "Напиши команду, которая выведет слово Hello на экран.",
        "placeholder": "print(...)",
        "correct_answers": ["print('Hello')", 'print("Hello")'],
        "explanation": "Для вывода текста в Python используется функция print().",
        "order_index": 2,
    },
    {
        "topic": "python",
        "type": "choice",
        "prompt": "Как создать список с числами 1, 2 и 3?",
        "options": ["(1, 2, 3)", "[1, 2, 3]", "{1, 2, 3}", "list(1, 2, 3)"],
        "correct_answers": ["[1, 2, 3]"],
        "explanation": "Списки создаются в квадратных скобках.",
        "order_index": 3,
    },
    {
        "topic": "python",
        "type": "input",
        "prompt": "Есть список items. Как взять первый элемент?",
        "placeholder": "items[...]",
        "correct_answers": ["items[0]"],
        "explanation": "Индексация в Python начинается с нуля.",
        "order_index": 4,
    },
    {
        "topic": "python",
        "type": "choice",
        "prompt": "Что вернет len('frog')?",
        "options": ["3", "4", "5", "Ошибка"],
        "correct_answers": ["4"],
        "explanation": "Во фразе frog четыре символа.",
        "order_index": 5,
    },
    {
        "topic": "python",
        "type": "input",
        "prompt": "Напиши заголовок функции greet с параметром name.",
        "placeholder": "def ...",
        "correct_answers": ["def greet(name):"],
        "explanation": "Функции объявляются через def имя(параметры):",
        "order_index": 6,
    },
    {
        "topic": "python",
        "type": "choice",
        "prompt": "Как добавить x в конец списка numbers?",
        "options": [
            "numbers.add(x)",
            "numbers.push(x)",
            "numbers.append(x)",
            "append(numbers, x)",
        ],
        "correct_answers": ["numbers.append(x)"],
        "explanation": "Для списков используется метод append().",
        "order_index": 7,
    },
    {
        "topic": "python",
        "type": "input",
        "prompt": "Напиши строку цикла for, который идет по числам от 0 до 4.",
        "placeholder": "for ...",
        "correct_answers": ["for i in range(5):"],
        "explanation": "range(5) создает последовательность 0, 1, 2, 3, 4.",
        "order_index": 8,
    },
    {
        "topic": "python",
        "type": "choice",
        "prompt": "Какой тип данных у значения 'text'?",
        "options": ["str", "int", "bool", "list"],
        "correct_answers": ["str"],
        "explanation": "Текстовые значения в Python имеют тип str.",
        "order_index": 9,
    },
    {
        "topic": "python",
        "type": "input",
        "prompt": "Как создать переменную score со значением 10?",
        "placeholder": "score = ...",
        "correct_answers": ["score = 10"],
        "explanation": "Переменная создается через имя, знак = и значение.",
        "order_index": 10,
    },
]
